language: cpp
compiler:
- clang
python:
- '2.7'
sudo: required
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libclang1-3.4
- git clone --recursive https://github.com/rice-solar-physics/rsp_toolkit.git ../rsp_toolkit
install:
- sudo pip install cldoc
- sudo pip install ghp-import
script:
- python build_docs.py
- ghp-import -m "Build docs" -b gh-pages docs/html
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} gh-pages
env:
  global:
    secure: "6imvUcU4bv4T0z3B+NPEC0xTkmgMepkf6gNZPkwZlSUxDxpvIhKyXm6qUduAFLRh110lJtYx0dkKP8pRFlj4rHMWgArnlSzIai03PSqERMRX2vTiZnSjjgMtV07TQ/vnXQdhfDM0QFxuYZPoLQqjZyUfP2XFan+sUyjnhHMX5uiYzXXTtKpEkX3QPquGCR2bUYJpOLwY7iPQf+U69uxPB1x7U8MYSMwCiAB0CJ3b80qEKKgrYMnnE8eSkomgcIkUyK0+mpp525fwCmT0ohx7cZ04t1bjQKkQTzurdqF+V0uDFkldNz/Ra1yJfNipPpdqhVLq2AOVV+/XaNoa1K4BcsjhmFEGrusBhsNp7s8eyrUMOQbiu8n11zH2b2QU5e5n5SdXV3mVDQ4csthvJt7ZWHxqE54/Y86jfhhxYYgQ0l+zvXmvYDUpY0/cVfRAgdR49X5MJMci30hjNC+cYp4ywZpyEv0/mq94MA5iGAYUZxfOhYO6gmGLIJw0GwhhwHh/k8xAN6L8lrDsV+GyunHyOui9zPoptsQVBvIRNIVOpdE0URaGuUAuAVVKol8h7tVQ0kbDS+SU9BJVMcO6IoAZAaY/63O3SmTtB7+QZHe218757nrKOsBN0NZHW+8B8z/YABcW6vubcMjvU2SbiE0Z72Tiw3YtR4AD25AlPpwADLY="
