language: cpp
compiler:
- clang
python:
- '2.7'
sudo: required
branches:
  only:
  - master
install:
- sudo pip install cldoc
- sudo pip install ghp-import 
script:
- python build_docs.py
- ghp-import -m "Build docs" -b gh-pages docs/html
- git push -f https://rice-solar-physics@github.com/${TRAVIS_REPO_SLUG} gh-pages
#env:
#	global:
#		secure: 